### ISSUE TITLE
separation of roles: registry.owner, vault.owner and committee

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#290]
1. Restore the separation between vault.owner and registry owner

2. Set the setters as follows:

## `HATVaultsRegistry.owner` --> this will be HATS GOVERNANCE

GLOBAL SETTINGS
- [x]  can call `setFeeSetter` set the feeSetter role
- [x]  can call `setWithdrawRequestParams` set time limits for withdrawal requests 
- [x]  can call `setWithdrawSafetyPeriod` set the amount of time during which claims can be submitted; during this time the vault users can not withdraw their funds. Must be less than 6 hours
- [x]  can call `setHatVestingParams` set vesting paramaters for bounty paid in hats
- [x]  can call `setMaxBountyDelay` to set the timelock delay for setting the max bounty

DEFAULT SETING OVERRIDABLE  BY VAULT
- [x]  can call `setClaimFee` set fee for submitting a vulnerability 
- [x]   `setArbitrator` set the arbitrator role 
- [x]   `setChallengePeriod` to set the time during which a claim can be challenged by the arbitrator 
- [x]   `setChallengeTimeOutPeriod` to set the time after which a challenged claim is automatically dismissed
- [ ]  set the part of the bounty that goes to governance - see #291 

OTHER FUNCTIONS

- [x] can call `swapSend` and swap, burn, and send the vauit's token that are earmarked for payout (after approveClaim)
- [x] `updateVisibility` 
- [ ]  `emergencyPause` **new** - used when stuff goes wrong, pauses deposits, transfers, stop submission of claims.  see #303 

## `HatVault.owner` --> THE OWNER OF THE VAULT, WHICH WILL BE HATS GOVERNANCE BY DEFAULT BUT CAN BE GIVEN LATER TO "THE PROJECT"

The `owner` of a HATvault created by the registry is the same as the registry owner (i.e. hat gov timelock)

- [x]  can call `transferOwnership` and `renounceOwnership` of `HATVaults`
- [x]  `setDepositPause` - stops/starts deposits, used on vault creation, or when vault is quite big
- [ ]  `setVaultDescription` 
- [x]  can call `setVestingParams` set vesting parameters for bounty paid in vault's token 
- [ ]  can call `setBountySplit` set how the bounty is split between security researcher, committee --> see #291 
- [ ]  can call `setCommittee`  (**what changes here is that the committeee can not call setCommittee anymore**)
- [x]  can call `setRewardController`  and set the reward controller 

## `HATVault.committee` (committee of each vault, set on creation) - RESPONSIBLE FOR ARBITRAGE OF CLAIMS

- [ ]  can call `submitClaim` - submit a claim for a bounty payout
- [x]  `setPendingMaxBounty` - set a pending request for the maximum percentage of the vault that can be paid out as a bounty.
- [x]  `setMaxBounty` - set the vault's max bounty to the already pending max bounty, after the time delay (of HATVaultsRegistry.GeneralParameters.setMaxBountyDelay) had passed.

**Comment by ben-kaufman** [comment]
Should the owner always be the registry owner (ie the timelock by default) or should that be possible to pass as an argument on createVault?

**Comment by ben-kaufman** [comment]
Also, I'd say the update description and the set pending and max bounty should be managed by the same role no?

**Comment by ben-kaufman** [comment]
Also, withdraw fees should always be paid to the registry owner right? (i.e hats governance)

**Comment by ben-kaufman** [comment]
Also now should we disallow arbitrator change and times of challenge change when there is an existing claim and on safety period (like with the bounty split)?

**Comment by lirona** [comment]
my opinion on some stuff:
- `updateVisibility` - should be hats gov
- `setArbitrator` - for sure should be gov, because it's one arbitrator for all vaults (defined in registry), do we want to allow each vault to set its own arbitrator? doesn't sound like a good idea to me
- also `setChallengePeriod` and `setChallengeTimeOutPeriod` i think should be gov and not project, the project should set it too short to try to avoid paying out
- `updateDescription` i think should be project
- `pause/unpause` - we are talking about pausing deposits or also withdrawals?
- `setVestingParams` i think should be project, it's their token :)

not sure about these:
- setBountySplit
- setCommittee
- setRewardController
- setPendingMaxBounty
- setMaxBounty

**Comment by jellegerbrandy** [comment]
> Should the owner always be the registry owner (ie the timelock by default) or should that be possible to pass as an argument on createVault?

Argument


> Also, I'd say the update description and the set pending and max bounty should be managed by the same role no?

I agree and changed the text in the issue - it is all set by the vault owner

> Also, withdraw fees should always be paid to the registry owner right? (i.e hats governance)

yes


> Also now should we disallow arbitrator change and times of challenge change when there is an existing claim and on safety period (like with the bounty split)?

Yes good call, we definitely do

**Comment by ben-kaufman** [comment]
For set/Pending/MaxBounty, should we exclude this from the timelock controller, so that while the owner is governance it will not be subject to delay (like before when it was owner by committee)

**Comment by ben-kaufman** [comment]
Also:
1. Should we allow to pass the owner on createVault or make it registry owner? (Remember if we keep it registry owner, then changing it will have the time delay)
2. Should we pass the committee on createVault or make it msg.sender?
3. Should we pass the isPaused on createVault or should we just remove it and have vaults created always unpaused?

**Comment by jellegerbrandy** [comment]
1. Pass the owner
2. pass the committee (we can talk)
3. I think passing paused is good
4.
